kind = "mobile"
previewPath = "/podcast-visualizer-mobile/"
title = "Podcast Visualizer Mobile"
version = "1.0.0"
id = "artifacts/podcast-visualizer-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/podcast-visualizer-mobile/" ]
localPort = 21567

[services.development]
run = "pnpm --filter @workspace/podcast-visualizer-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/podcast-visualizer-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/podcast-visualizer-mobile", "run", "serve" ]

[services.env]
PORT = "21567"
BASE_PATH = "/podcast-visualizer-mobile/"
