const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#8B5CF6",
    background: "#FAFAFA",
    foreground: "#18181B",
    card: "#FFFFFF",
    cardForeground: "#18181B",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#F4F4F5",
    secondaryForeground: "#18181B",
    muted: "#F4F4F5",
    mutedForeground: "#71717A",
    accent: "#8B5CF6",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E4E4E7",
    input: "#E4E4E7",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#8B5CF6",
    background: "#0F0F0F",
    foreground: "#FFFFFF",
    card: "#18181B",
    cardForeground: "#FFFFFF",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#27272A",
    secondaryForeground: "#FAFAFA",
    muted: "#27272A",
    mutedForeground: "#A1A1AA",
    accent: "#8B5CF6",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#2A2A2A",
  },
  radius: 10,
};

export default colors;
